name: CI pour TP Workflow (Java 22 - Gradle)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Donner les permissions d'exécution à Gradle
        run: chmod +x gradlew

      - name: Vérifier et compiler le projet
        run: ./gradlew build --no-daemon

      - name: Lancer les tests
        run: ./gradlew test --no-daemon

      - name: Vérifier le code avec Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest --no-daemon

      - name: Construire l'artefact
        run: ./gradlew assemble --no-daemon
